<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            ['id' => 1, 'name' => 'Lucas Matheus', 'email' => 'lucasmsilvam01@gmail.com', 'email_verified_at' => null, 'password' => bcrypt('123Lucas'), 'categoryId' => 1, 'lowDescription' => 'Adm', 'longDescription' => 'Administrador', 'remember_token' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 2, 'name' => 'Lucas Almeida', 'email' => 'lucas.almeida@example.com', 'email_verified_at' => null, 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Apaixonado por tecnologia.', 'longDescription' => 'Desenvolvedor web com experiência em PHP e Laravel.', 'remember_token' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 3, 'name' => 'Maria Clara', 'email' => 'maria.clara@example.com', 'email_verified_at' => null, 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Adora arte e design.', 'longDescription' => 'Designer gráfico especialista em branding e UX.', 'remember_token' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 4, 'name' => 'João Pedro', 'email' => 'joao.pedro@example.com', 'email_verified_at' => null, 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Fã de esportes.', 'longDescription' => 'Treinador de futebol e apaixonado por competições esportivas.', 'remember_token' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 5, 'name' => 'Ana Luiza', 'email' => 'ana.luiza@example.com', 'email_verified_at' => null, 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Entusiasta de moda.', 'longDescription' => 'Estilista com experiência em coleções minimalistas.', 'remember_token' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 6, 'name' => 'Carlos Silva', 'email' => 'carlos.silva@example.com', 'email_verified_at' => null, 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Engenheiro apaixonado.', 'longDescription' => 'Engenheiro civil focado em sustentabilidade.', 'remember_token' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 7, 'name' => 'Beatriz Costa', 'email' => 'beatriz.costa@example.com', 'email_verified_at' => null, 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Ama animais.', 'longDescription' => 'Veterinária dedicada a resgates e cuidados de pets.', 'remember_token' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 8, 'name' => 'Fernando Mendes', 'email' => 'fernando.mendes@example.com', 'email_verified_at' => null, 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Gamer e streamer.', 'longDescription' => 'Criador de conteúdo de jogos e competitivo em eSports.', 'remember_token' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 9, 'name' => 'Gabriela Souza', 'email' => 'gabriela.souza@example.com', 'email_verified_at' => null, 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Culinária é sua paixão.', 'longDescription' => 'Chef especializada em pratos tradicionais brasileiros.', 'remember_token' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 10, 'name' => 'Rafael Martins', 'email' => 'rafael.martins@example.com', 'email_verified_at' => null, 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Fã de tecnologia.', 'longDescription' => 'Desenvolvedor de software com foco em soluções mobile.', 'remember_token' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 11, 'name' => 'Ana Silva', 'email' => 'ana.silva@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Curiosa sobre tecnologia', 'longDescription' => 'Amo tecnologia e inovação, sempre buscando aprender mais', 'remember_token' => 'random_token_1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 12, 'name' => 'Carlos Oliveira', 'email' => 'carlos.oliveira@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Entusiasta de videogames', 'longDescription' => 'Jogador apaixonado por jogos de aventura e RPG', 'remember_token' => 'random_token_2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 13, 'name' => 'Fernanda Souza', 'email' => 'fernanda.souza@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Amante de livros', 'longDescription' => 'Adoro ler ficção científica e mistério, sempre em busca de boas histórias', 'remember_token' => 'random_token_3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 14, 'name' => 'Marcos Pereira', 'email' => 'marcos.pereira@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Fotógrafo amador', 'longDescription' => 'A fotografia me permite capturar momentos únicos da vida', 'remember_token' => 'random_token_4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 15, 'name' => 'Juliana Lima', 'email' => 'juliana.lima@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Viciada em filmes', 'longDescription' => 'Cinema é a minha paixão, sempre em busca de novos filmes para assistir', 'remember_token' => 'random_token_5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 16, 'name' => 'Paulo Costa', 'email' => 'paulo.costa@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Programador autodidata', 'longDescription' => 'Meu maior objetivo é me tornar um grande desenvolvedor', 'remember_token' => 'random_token_6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 17, 'name' => 'Beatriz Martins', 'email' => 'beatriz.martins@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Amante da natureza', 'longDescription' => 'Passeios ao ar livre e contato com a natureza me trazem paz', 'remember_token' => 'random_token_7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 18, 'name' => 'Roberto Mendes', 'email' => 'roberto.mendes@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Fã de música', 'longDescription' => 'Música é minha paixão, não consigo viver sem ela', 'remember_token' => 'random_token_8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 19, 'name' => 'Larissa Almeida', 'email' => 'larissa.almeida@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Viagens pelo mundo', 'longDescription' => 'Explorar novas culturas e lugares ao redor do mundo é meu objetivo de vida', 'remember_token' => 'random_token_9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 20, 'name' => 'Luiz Fernando', 'email' => 'luiz.fernando@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Apaixonado por esportes', 'longDescription' => 'Jogos coletivos me motivam e me ajudam a manter um estilo de vida saudável', 'remember_token' => 'random_token_10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 21, 'name' => 'Mariana Santos', 'email' => 'mariana.santos@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Fã de culinária', 'longDescription' => 'Cozinhar é minha forma de expressão artística', 'remember_token' => 'random_token_11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 22, 'name' => 'Vitor Gomes', 'email' => 'vitor.gomes@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Aficionado por carros', 'longDescription' => 'Adoro carros e tudo relacionado ao universo automotivo', 'remember_token' => 'random_token_12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 23, 'name' => 'Giovanna Rocha', 'email' => 'giovanna.rocha@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Viajante', 'longDescription' => 'Minhas viagens sempre trazem novas perspectivas e histórias para contar', 'remember_token' => 'random_token_13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 24, 'name' => 'Ricardo Barbosa', 'email' => 'ricardo.barbosa@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Empreendedor', 'longDescription' => 'Sempre buscando novas formas de melhorar a minha carreira e meus projetos', 'remember_token' => 'random_token_14', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 25, 'name' => 'Sofia Costa', 'email' => 'sofia.costa@email.com ', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Estudante de design', 'longDescription' => 'Meu foco é no design gráfico e em criar visuais impactantes', 'remember_token' => 'random_token_15', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 26, 'name' => 'André Machado', 'email' => 'andre.machado@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Gamer', 'longDescription' => 'Jogo por diversão e para relaxar, adoro desafios', 'remember_token' => 'random_token_16', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 27, 'name' => 'Cláudia Pires', 'email' => 'claudia.pires@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Viciada em moda', 'longDescription' => 'A moda é minha forma de expressar quem sou e como vejo o mundo', 'remember_token' => 'random_token_17', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 28, 'name' => 'Felipe Ribeiro', 'email' => 'felipe.ribeiro@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Tecnologia', 'longDescription' => 'Sou apaixonado por tecnologia e novidades no mundo da informática', 'remember_token' => 'random_token_18', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 29, 'name' => 'Camila Rocha', 'email' => 'camila.rocha@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 2, 'lowDescription' => 'Aficionada por história', 'longDescription' => 'Adoro estudar história e aprender sobre as culturas antigas', 'remember_token' => 'random_token_19', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 30, 'name' => 'Eduardo Silva', 'email' => 'eduardo.silva@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Arquiteto', 'longDescription' => 'Trabalho com design de interiores e adoro projetar espaços', 'remember_token' => 'random_token_20', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 31, 'name' => 'Isabela Ferreira', 'email' => 'isabela.ferreira@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Apaixonada por viagens', 'longDescription' => 'Explorar novos destinos é a minha paixão', 'remember_token' => 'random_token_21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 32, 'name' => 'Gabriel Lima', 'email' => 'gabriel.lima@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Desenvolvedor web', 'longDescription' => 'Programar e criar soluções inovadoras é o que me motiva', 'remember_token' => 'random_token_22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 33, 'name' => 'Renata Barbosa', 'email' => 'renata.barbosa@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Yoga e bem-estar', 'longDescription' => 'Pratico yoga e acredito no equilíbrio entre mente e corpo', 'remember_token' => 'random_token_23', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 34, 'name' => 'Leonardo Rocha', 'email' => 'leonardo.rocha@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Cozinheiro amador', 'longDescription' => 'Cozinhar e experimentar receitas novas é o meu hobby', 'remember_token' => 'random_token_24', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 35, 'name' => 'Patricia Gomes', 'email' => 'patricia.gomes@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Apaixonada por literatura', 'longDescription' => 'Livros são meus melhores amigos, sempre lendo novos autores', 'remember_token' => 'random_token_25', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 36, 'name' => 'Felipe Martins', 'email' => 'felipe.martins@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Atleta', 'longDescription' => 'Me dedico aos treinos diários para melhorar minha performance', 'remember_token' => 'random_token_26', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 37, 'name' => 'Camila Santos', 'email' => 'camila.santos@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Mãe e profissional', 'longDescription' => 'Conciliar a maternidade com a carreira é um grande desafio, mas adoro', 'remember_token' => 'random_token_27', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 38, 'name' => 'Rafael Silva', 'email' => 'rafael.silva@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Designer gráfico', 'longDescription' => 'Criar visuais que impactam as pessoas é o que me faz feliz', 'remember_token' => 'random_token_28', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 39, 'name' => 'Adriana Costa', 'email' => 'adriana.costa@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Fã de gastronomia', 'longDescription' => 'Explorar diferentes sabores e técnicas culinárias é minha paixão', 'remember_token' => 'random_token_29', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 40, 'name' => 'Cláudia Almeida', 'email' => 'claudia.almeida@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Artista', 'longDescription' => 'Minhas obras expressam minha visão do mundo e da sociedade', 'remember_token' => 'random_token_30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 41, 'name' => 'Bruno Pereira', 'email' => 'bruno.pereira@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Fã de fotografia', 'longDescription' => 'Fotografar momentos especiais e capturar a essência das pessoas é minha paixão', 'remember_token' => 'random_token_31', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 42, 'name' => 'Gabriela Martins', 'email' => 'gabriela.martins@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Arquiteta', 'longDescription' => 'Transformo espaços através da arquitetura, criando ambientes funcionais e estéticos', 'remember_token' => 'random_token_32', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 43, 'name' => 'Rodrigo Souza', 'email' => 'rodrigo.souza@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Jogador profissional', 'longDescription' => 'Competir é minha vida, e estou sempre em busca do meu próximo campeonato', 'remember_token' => 'random_token_33', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 44, 'name' => 'Isabela Ribeiro', 'email' => 'isabela.ribeiro@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Comunicativa', 'longDescription' => 'Falar em público é minha especialidade, adoro eventos e palestras', 'remember_token' => 'random_token_34', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 45, 'name' => 'Marcos Costa', 'email' => 'marcos.costa@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Empreendedor de startups', 'longDescription' => 'Gosto de resolver problemas e criar soluções inovadoras', 'remember_token' => 'random_token_35', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 46, 'name' => 'Renata Lima', 'email' => 'renata.lima@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Chef de cozinha', 'longDescription' => 'Transformo alimentos em experiências deliciosas', 'remember_token' => 'random_token_36', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 47, 'name' => 'Vinícius Oliveira', 'email' => 'vinicius.oliveira@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'category Id' => 3, 'lowDescription' => 'Futurista', 'longDescription' => 'Estou sempre pensando no futuro e em como a tecnologia pode mudar nossas vidas', 'remember_token' => 'random_token_37', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 48, 'name' => 'Paula Souza', 'email' => 'paula.souza@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Viajante do mundo', 'longDescription' => 'Explorar culturas e lugares desconhecidos é o que mais me fascina', 'remember_token' => 'random_token_38', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 49, 'name' => 'Lucas Martins', 'email' => 'lucas.martins@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Desenvolvedor de jogos', 'longDescription' => 'Programar e criar mundos virtuais é a minha maior paixão', 'remember_token' => 'random_token_39', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 50, 'name' => 'Eduarda Pereira', 'email' => 'eduarda.pereira@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Cientista', 'longDescription' => 'A pesquisa científica me fascina, especialmente no campo da biologia molecular', 'remember_token' => 'random_token_40', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 51, 'name' => 'Hugo Costa', 'email' => 'hugo.costa@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Filósofo', 'longDescription' => 'Gosto de questionar o mundo ao meu redor e refletir sobre o nosso lugar nele', 'remember_token' => 'random_token_41', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 52, 'name' => 'Catarina Rocha', 'email' => 'catarina.rocha@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Psicóloga', 'longDescription' => 'Estudar o comportamento humano e ajudar pessoas a superarem seus desafios é minha missão', 'remember_token' => 'random_token_42', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 53, 'name' => 'Thiago Silva', 'email' => 'thiago.silva@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Designer digital', 'longDescription' => 'Minha missão é criar designs que sejam ao mesmo tempo estéticos e funcionais', 'remember_token' => 'random_token_43', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 54, 'name' => 'Ricardo Lima', 'email' => 'ricardo.lima@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Entusiasta de tecnologia', 'longDescription' => 'Adoro aprender sobre novas tecnologias e seu impacto no mundo', 'remember_token' => 'random_token_44', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 55, 'name' => 'Samantha Souza', 'email' => 'samantha.souza@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 3, 'lowDescription' => 'Aficionada por arte', 'longDescription' => 'Pintura, escultura e arte digital são minhas formas de expressão', 'remember_token' => 'random_token_45', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 56, 'name' => 'Rafael Almeida', 'email' => 'rafael.almeida@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Educador', 'longDescription' => 'Ensinar é minha missão de vida, e acredito que a educação transforma realidades', 'remember_token' => 'random_token_46', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 57, 'name' => 'Juliana Santos', 'email' => 'juliana.santos@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Dançarina', 'longDescription' => 'A dança é minha forma de me expressar e me conectar com o mundo', 'remember_token' => 'random_token_47', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 58, 'name' => 'Daniela Costa', 'email' => 'daniela.costa@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Mentora de carreira', 'longDescription' => 'Ajudo profissionais a alcançarem seus objetivos e se destacarem no mercado', 'remember_token' => 'random_token_48', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 59, 'name' => 'Felipe Costa', 'email' => 'felipe.costa@email.com', 'email_verified_at' => '2024-11-16 08:00:00', 'password' => bcrypt('senha123'), 'categoryId' => 4, 'lowDescription' => 'Tecnólogo', 'longDescription' => 'Meu trabalho é otimizar processos através da aplicação de novas tecnologias', 'remember_token' => 'random_token_49', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}
